version: "3.9"
services:

  postgres-db:
    container_name: postgres-db
    image: postgres:14.1
    volumes:
      - postgres_data:/docker/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5  
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    volumes:
      - seq_data_container:/docker/data/seq
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3  



volumes:
  postgres_data:
  seq_data_container:

  
